name: docker

on:
  push:

jobs:
  before:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "not contains '[skip ci]'"

  build:
    needs: before

    strategy:
      matrix:
        nim_version:
          - 1.2.0
          - latest

    runs-on: ubuntu-latest
    container: nimlang/nim:${{ matrix.nim_version }}-alpine

    steps:
      - name: Dump versions
        run: |
          nim -v
          nimble -v

      - uses: actions/checkout@v2

      - name: Run test(s)
        run:  nimble test

      - name: Install MinGW
        run:  apk add mingw-w64-gcc

      - name: Build x64@win
        run:  nim c -d:mingw --cpu:amd64 src/dbs

      - name: Build x32@win
        if:   false
        run:  nim c -d:mingw --cpu:i386 src/dbs
