name: exe

on:
  push:

jobs:
  before:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "not contains '[skip ci]'"

  build:
    runs-on: ubuntu-latest
    needs: before
    steps:
      - name: Install MinGW
        run:  sudo apt install mingw-w64

      - uses: actions/checkout@v2

      - name: Set cache-key
        id: vars
        run: echo ::set-output name=cache-key::$(date +%Y-%m-%d)

      - name: Print cache-key
        run: echo cache-key = ${{ steps.vars.outputs.cache-key }}

      - name: Cache choosenim
        id: cache-choosenim
        uses: actions/cache@v1
        with:
          path: ~/.choosenim
          key: ${{ runner.os }}-choosenim-${{ steps.vars.outputs.cache-key }}

      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v1
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}

      - uses: jiro4989/setup-nim-action@v1

      - name: Dump versions
        run: |
          nim -v
          nimble -v

      - name: Build x64
        run:  nim c -d:mingw -d:release --cpu:amd64 -o:dbs-64.exe src/dbs.nim

      - name: Build x86
        run:  nim c -d:mingw -d:release --cpu:i386  -o:dbs-32.exe src/dbs.nim

      - name: Run UPX
        run:  upx *.exe

      - name: Upload exe
        uses: actions/upload-artifact@v2
        with:
          name: win
          path: ./*.exe
