name: Scoop

on:
  - push

jobs:
  x32:
    runs-on: windows-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Install scoop
        run:  |
          iwr -useb get.scoop.sh | iex

      - name: Add to PATH
        run:  echo ::add-path::$USERPROFILE/scoop/shims
        shell: bash

      - name: Show PATH
        run:  echo $PATH

      - name: Install Nim
        run: scoop install nim -i -a 32bit

      - name: Show versions
        run:  |
          nim -v
          nimble -v

      - name: Run test(s)
        run: nimble test -d:mingw
