name: Tests

on:
  - push

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Install mingw
        run:  sudo apt install mingw-w64

      - name: setup Nim
        uses: jiro4989/setup-nim-action@v1

      - name: Check out
        uses: actions/checkout@v2

      - name: Install dependencies
        run:  nimble install

      - name: Run tests
        run:  nimble test

      - name: Run binary
        run:  nim c -r src/dbs.nim

      - name: Cross compile
        run:  |
          nim c -d:mingw --cpu:amd64 -o:dbs-64.exe src/dbs.nim
          nim c -d:mingw --cpu:i386  -o:dbs-32.exe src/dbs.nim
