name: Tests

on:
  - push

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - setup Nim
        uses: jiro4989/setup-nim-action@v1

      - name: Check out
        uses: actions/checkout@v2

      - name: Install dependencies
        run:  nimble install

      - name: Run tests
        run:  nimble test
