name: GitHubPages

on:
  - push

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Install choosenim
        run:  curl https://nim-lang.org/choosenim/init.sh -sSf | bash -s -- -y

      - name: Add to PATH
        run:  echo ::add-path::$HOME/.nimble/bin

      - name: Check out
        uses: actions/checkout@v2

      - name: Install dependencies
        run:  nimble install

      - name: Run tests
        run:  nimble test
