name: win

on:
  - push

jobs:
  testing:
    runs-on: windows-latest

    steps:
      - name: setup Nim
        uses: jiro4989/setup-nim-action@v1

      - name: Check out
        uses: actions/checkout@v2

      - name: Install dependencies
        run:  nimble install

      - name: Run tests
        run:  nimble test

      - name: Build x64 app
        run:  nim c src/dbs

      - name: Run x64 app
        run:  src/dbs

      - name: Build x32 app
        run:  nim c -d:mingw --cpu:i386 src/dbs

      - name: Run x32 app
        run:  src/dbs
