name: win

on:
  - push

jobs:
  testing:
    runs-on: windows-latest

    steps:
      - name: Install choosenim
        run:  curl https://nim-lang.org/choosenim/init.sh -sSf | bash -s -- -y
        shell: bash

      - name: Add to PATH
        run:  echo ::add-path::$USERPROFILE/.nimble/bin
        shell: bash

      - name: Show PATH
        run:  echo $PATH
        shell: bash

      - name: Show PATH again
        run:  path
        shell: cmd

      - name: Check out
        uses: actions/checkout@v2

      - name: Install dependencies
        run:  nimble install

      - name: Run tests
        run:  nimble test
