name: win

on:
  - push

jobs:
  testing:
    runs-on: windows-latest

    steps:
      - name: setup Nim
        uses: jiro4989/setup-nim-action@v1

      - name: Check out
        uses: actions/checkout@v2

      - name: Install dependencies
        run:  nimble install

      - name: Run tests
        run:  nimble test

      - name: Run tests @x86
        run:  nimble test --cpu:i386
